= Multi-Signature Scripts on Cardano - Mac OSX
:author: Jack O'Brien
:imagesdir: images
:source-highlighter: highlight.js
:highlightjs-theme: ocean
:icons: font
:toc:
:experimental:

:url-daedalus: https://daedaluswallet.io/
:url-daedalus-tn: https://developers.cardano.org/en/testnets/cardano/get-started/wallet/
:url-vscode:   https://code.visualstudio.com/
:url-faucet:   https://developers.cardano.org/en/testnets/cardano/tools/faucet/s
:url-playlist: https://www.youtube.com/playlist?list=PLKl4dqDtindkquPR7EVknxtBPCtdM1vDr

== Introduction
The aim of these tutorial notes are to demostrate how to use Multi-Signature scripts on Cardano using the commandline 
tool `cardano-cli` on Microsoft Windows. The notes are a bonus set of documentation for a series of {url-playlist}[tutorial videos]. Everything 
is done on a Cardano *Testnet* so you don't need to buy Ada or spend Ada to complete the steps. 
Everything shown works on the Cardano Mainnet too. You will need to make a few changes to the commandline options.

The tutorial shows how to take advantage of Cardano's native multi-signature support. **Scripts** are a way of allowing an unspent transaction outputs to be used as an input to a new transaction if a pre-defined combination of signatures is provided. e.g Two people having to sign a transaction simultaneously.

We'll be using the **Cardano Node** that is installed with {url-daedalus}[Daedalus], the full-node wallet for Cardano. {url-daedalus}[Daedalus] works on Microsoft Windows, Apple Mac OSX, and Linux. 

This tutorial is for Mac OSX, and there is a companion tutorial for Mircosoft Windows 10. 

To make the tutorials consistent across platforms I'll be using Microsoft Visual Studio ( {url-vscode}[VSCode] ). By opening this file in VSCode, or https://github.com/atMetaphor/Metaphor-Tutorials[in your browser] you can copy/paste and change the parameters around directly within {url-vscode}[VSCode]. I'll be using VSCode in future tutorials so this is a way to introduce things. This does however mean you'll need to install {url-vscode}[VSCode]. 

If you don't want to do that, you will still be able to follow along easily enough using just a pwershell terminal window.

=== Videos
This document is a bonus video for a series of short {url-playlist}[tutorial videos].

== Getting Started - Script Types

It's important that you have already completed the native token tutorial videos and familiarised yourself with how things are set up. If not go and check out these {url-playlist}[Tutorials] as you will need context with reguards to the UTXO model and how transactions are built. Before we start with anything there are three types of multi-signature script types.

All :: The first being the `type` `all` indicating that `all` keys must be used to witness and sign and spend a transaction based on the coresponding payment key hashes listed.
Any :: The `type` `Any` being that any one key listed in the coresponding script can be used to witness and sign a transaction.
At Least :: Lastly, the `type` `atLeast`, specifies that 2 or more keys listed in the coresponding script are required to witness and sign a transaction for it to be spent.

Multi-Sig scripts allow for unspent transactions to be spent under a pre-defined combination of signatures. Depending on the type of script provided, it's a way of collectively choosing how you want, say, a pool of tokens to be spent for example.

== Using Multisignature Scripts

Let's go ahead and walk through how a multiscript works and how it runs. Involving the creation of some new keys and the multi-signature script. Followed by the gathering of the required witnesses in order to spend a basic transaction. I will be using the `all` type script to demonstrate this, Feel free to play around with the other types.

=== Creating a Bash Terminal
Before we begin, it's essential that we set up our environment appropriately in order for this process to function properly

Open up {url-vscode}[VSCode] then kbd:[Ctrl + Shift + `] to open up a Bash shell terminal.

[NOTE] 
By default your terminal is typically set to using the default  shell. This may be Bash or ZShell. Either is fine and I'll use *shell session* or *Bash* to mean either.

Next we need to setup the filesystem locations for the `cardano-cli`, the communication channel between `cardano-cli` and the running *Cardano Node*, and a magic number identifying the Testnet we're using. These settings will be used in our shell session. 

[source,bash]
----
alias cardano-cli="/Applications/Daedalus\ Testnet.app/Contents/MacOS/cardano-cli" <1>

export CARDANO_NODE_SOCKET_PATH=~/Library/Application\ Support/Daedalus\ Testnet/cardano-node.socket <2>

export MAGICID=1097911063 <3> <4>
----
<1> Linking our `cardano-cli` that came with {url-daedalus-tn}[Daedalus].
<2> Mapping the socket id to interface with the Cardano node on {url-daedalus}[Daedalus].
<3> Creating an environment variable with the network magic number for the Testnet.
<4> This network magic ID is specfic to the shelly testnet. If you want to access the mainnet you can find the network magic number {url-cardanoConfig}[here] under shelleyGenesis.

[WARNING]
If you installed {url-daedalus-tn}[Daedalus Testnet] into a different location than the default used above, you'll need to change the paths to reflect the alternative location.

These commands must be re-entered everytime you start a new shell. To save some time you can set up the alias, path, and MAGICID variables in the your `.bashrc`or `.zshrc` file found in your `$HOME` directory. That way you don't have to enter them into the shell everytime. 

=== Generating the Script Address

You will first need to generate new payment keys to generate the necessary key hashes, which will be put into our signature script.

[source,bash]
----
cardano-cli address key-gen \
  --verification-key-file payment1.vkey \
  --signing-key-file payment1.skey \
----

[IMPORTANT]
Repeat this step until you have 2 or 3 keys generated in your directory.

With our keys generated, we can now create our Multi-Signature Script. To do this we have to generate a JSON file (as the scripts are written as JSON objects) and hash our generated verification keys.

[source,bash]
----
touch multisig.json <1>

code multisig.json <2>
----
<1> Create a new multisig Json file using the touch command.
<2> Open the file in a new window in VSCode.

Copy and paste this basic script boilerplate in. If you wish to add more keys simply copy and paste in more keyhash objects. Make sure to stay within the structure of the document otherwise the script will be invalid when submitting the transaction.

[source,JSON]
----
{
    "scripts": [
        {
            "keyHash": "keyhash of verfication key 1", <1>
            "type": "sig" <2>
        },
        {
            "keyHash": "keyhash of verfication key 2",
            "type": "sig"
        },
        {
            "keyHash": "keyhash of verfication key 3",
            "type": "sig"
        }
    ],
    "type": "all" <3> <4>
}
----
<1> Our hash of the verfication key we generated earlier.
<2> The type of the key we are using in the script.
<3> The type of the script we are using, In the case of this tutorial we are using the "all" type script.
<4> If this were an `atLest` script we would add a `required` object above our `type` followed by how many keys needed say, 2 for example.

With the boilerplate copied and opened in a new tab we can go ahead and hash our verfication keys.

[source,bash]
----
cardano-cli address key-hash \
  --payment-verification-key-file pay1.vkey

08d2bfb72636c3214490b01c4fe17e565eea4033243aaa7c86958df5 <1>
----
<1> An example of what your keyhash will look like.

Copy an paste the result of the hash into the `keyhash` object in our multisig.json file. You will have to repeat this step depending on how many keys you generated. Your result will look something like this.

[source,Json]
----
{
    "scripts": [
        {
            "keyHash": "08d2bfb72636c3214490b01c4fe17e565eea4033243aaa7c86958df5",
            "type": "sig"
        },
        {
            "keyHash": "e2c7de38c0309b5f6536eeb7350e186faa6fb1cd500f1507a78e7023",
            "type": "sig"
        },
        {
            "keyHash": "2ae8838436219030f5095dc4331318c1ea188d3095f157640157d7e4",
            "type": "sig"
        }
    ],
    "type": "all"
}
----

=== Creating a Multi-Signature Address

With our keys hashed and saved into the script we can now generate an address from the script. This address is going to be unique only to the script that we created. So only the keys that we hashed and listed can be witness to this are the only ones that can spend from this generated address.

Go aheaad and generate the address using the following command.

[source,bash]
----
cardano-cli address build-script \
  --script-file ./multisig.json \
  --testnet-magic $MAGICID \
  --out-file multisig.addr
----

==== Sending some ADA

Before we move on it's best we send some ada from our daedalus wallet to the multi-signature address for us to spend.

[source,bash]
----
cat multisig.addr <1>

cardano-cli query utxo --address $(cat multisig.addr) --testnet-magic $MAGICID --mary-era <2>
----
<1> prints the readout of the file "multisig.addr". Copy the output and send some Lovelace.
<2> Checking if any transaction inputs came through and the Lovelace received.

=== Creating a Multisig Transaction

If you've done the previous tutorial in the {url-playlist}[minitng native assets on cardano] you will be familiar with building transactions. If your new to this, stop what you are doing and watch the first two videos before coming here.

The `raw` transaction for a multisig script is really no different to one without it. But instead of doing a transaction where only 1 person has to sign it were doing it with mulitple witnesses and signing keys with the optional addition of a ttl (time to live). This puts restrictions on how long the we have before the transaction dies and you have to start again.

==== Enviroment varables

Before we start, I'm going to first set up my environment variables. If you followed previous tutorials of mine, you'd know what I'm talking about. A simple story short is that they enable us to pass values easily by making them identifiable.

[source,bash]
----
export TXINID0="e45fdc75440593757374652163a0a1f03523dc7527de32bb74dc66a1dc5ead8f#0"
export LOVELACE0=1000000
export FEE=0
export OUTFILE="multisig.raw"
export WITNESSFILE="multisig.witness"
export SIGNEDFILE="multisig.signed"
export OUTADDR="addr_test1qru07t6cx49r372sz09huss5s62amfj34grckanm6vh0cd4plz8eefmaz9py8gej26e0xq4nlhzncajdr2av7mena49s5l55t6"
export OUTLOVELACE=5000000

cardano-cli query tip --testnet-magic=$MAGICID <1>

export SLOTNUM=27965677 <2>
----
<1> Tiping the block so I can catch the current slot. (quite the catchy rhyme too huh?)
<2> Putting the current slot number into an enviroment variable.

==== Building the Raw Transaction

 We can now go ahead and build the transaction. Note that this part can be very finicky and if subject to typos and spaces you will run into problems.

[source,Powershell]
----
cardano-cli transaction build-raw \
--mary-era \
--ttl $(expr $SLOTNUM + 2000) \ <1>
--fee $FEE \
--tx-in $TXINID \
--tx-out $(cat multisig.addr)+$(expr $LOVELACE0 + $OUTLOVELACE - $FEE) \
--tx-out "$OUTADDR+$OUTLOVELACE" \
--out-file $OUTFILE
----
<1> As mentioned before you have the current slot plus an arbitrary ammount added before the transaction can't be processed. This choice is entirely optional, so don't be afraid to take this out.

Calculate a fee and rebuild the `$FEE` variable. As soon as that is complete be sure to rebuild the raw transaction again before going ahead with the other steps.

[NOTE]
Make sure to set the correct parameters for your transaction in's and outs and the witness count, depending on how you set up the script parameters. Your witness count should match that by how many keys you put into the script.

[source,bash]
----
cardano-cli transaction calculate-min-fee \
  --tx-body-file $OUTFILE \
  --tx-in-count 2 \
  --tx-out-count 1 \
  --witness-count 3 \
  --testnet-magic $MAGICID \
  --protocol-params-file protocol.json
----

=== Witnessing and Signing the Transaction

With our transaction rebuilt, we start to move on to the witnessing part of the transaction. From this point onwards is where we start to deviate a little bit. Because we made a script of the type `All`, we have to make sure we witness and sign all those keys put into the script. Now it's not normal for us to hold all the keys to the castle, so to speak, but this being a tutorial, I think it's OK only to demonstrate the script's function here.

[source,bash]
----
cardano-cli transaction witness \
  --testnet-magic $MAGICID \
  --tx-body-file $OUTFILE \
  --script-file ./allMultiSigScript.json \
  --out-file $WITNESSFILE

  cardano-cli transaction witness \
  --testnet-magic $env:MAGICID \
  --tx-body-file $OUTFILE \
  --signing-key-file payment1.skey \
  --out-file "Key1_$WITNESSFILE"

    cardano-cli transaction witness \
  --testnet-magic $env:MAGICID \
  --tx-body-file $OUTFILE \
  --signing-key-file payment2.skey \
  --out-file "Key2_$WITNESSFILE"

    cardano-cli transaction witness \
  --testnet-magic $env:MAGICID \
  --tx-body-file $OUTFILE \
  --signing-key-file payment3.skey \
  --out-file "Key3_$WITNESSFILE"
----

You will have noticed having dones this, that we have 3 files in our directory named with the corressponding keys. Now that our witnesses have signed the transaction we can assemble it ready for submition on the testnet.

[source,bash]
----
cardano-cli transaction assemble \
  --tx-body-file $env:OUTFILE \
  --witness-file $env:WITNESSFILE \
  --witness-file "Key1_$WITNESSFILE" \
  --witness-file "Key2_$WITNESSFILE" \
  --witness-file "Key3_$WITNESSFILE" \
  --out-file $TXSIGNEDFILE
----


[source,bash]
----
  cardano-cli transaction submit \
  --tx-file $TXSIGNEDFILE \
  --testnet-magic $MAGICID

cardano-cli query utxo --address $(cat multisig.addr) --testnet-magic $MAGICID --mary-era <1>
----
<1> Check to see if the transaction completed!

With the transaction complete and the ada in our retrospective wallet. You should now have the knowledge to understand the basics of multi signature scripts. Go ahead and try out the different types and experiment with your friends.